### ISSUE TITLE
history is lost

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthlabpy#1]
hey @choldgraf i moved the earthlab module over here! i had attempted to preserve the entire history but that didn't work. I may try again but let me know if you think that history is imperative!

**Comment by choldgraf** [comment]
IMO it's OK to lose history...it'll still exist in the old repo anyway

**Comment by lwasser** [comment]
Ok! I may try one more time just to be able to do it BUT i'm with you. We have it in the other repo!
